config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { omniauth_callbacks: "users" }

  root 'pages#home'
  get 'about', to: 'pages#about', as: 'about'
  get 'gallery', to: 'pages#gallery', as: 'gallery'
  # root 'pages#coming_soon'
  # get 'home', to: 'pages#home', as: 'home'
  get 'coming_soon', to: 'pages#coming_soon', as: 'coming_soon'

  resources :codes, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :submissions, only: [:new, :create, :edit, :update, :destroy]
    member do
      put 'queue', as: 'queue'
      put 'dequeue', as: 'dequeue'
    end
  end

  put 'submissions/:id/vote', to: 'submissions#vote', as: 'vote'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/pages/about.html.erb
      <div class="cell cell--xl ptl">
        <h2 class="tac tch">The Team<br><span class="tfb twb">&#8964;</span></h2>
        <img src="<%= image_url('team.png') %>" alt="AJ, Hebah, and Jessica" class="db mhc">
        <div class="group table--m bca2">
          <div class="g-b--m--1of3 table-cell--m bca1 pal">
            <h2 class="mbf">AJ Foster</h2>
            <h4>Back-End Developer</h4>
            <p>A student of mathematics who is obsessed with "pretty" code. Ever since seeing someone write a program in the 7th grade, he has treated programming like another subject in his education. He firmly believes in the mantra "do not let school get in the way of your education."</p>
            <p>AJ loves thinking through problems from the perspective of a machine, and persuading computers to do what he wants through code. He enjoys back-end development for its diversity of both problems and solutions.</p>
            <p>AJ is taking suggestions on how to answer the question, <em>"why did you choose to study mathematics?"</em></p>
            <p class="tsxl mbf tac">
              <a href="https://twitter.com/austin_j_foster" class="tci mlxs mrxs"><svg class="icon"><use xlink:href="<%= image_url("icons.svg") %>#icon-twitter"></use></svg></a>
              <a href="https://github.com/aj-foster" class="tci mlxs mrxs"><svg class="icon"><use xlink:href="<%= image_url("icons.svg") %>#icon-github"></use></svg></a>
            </p>
          </div>
          <div class="g-b--m--1of3 table-cell--m bch pal">
            <h2 class="mbf">Hebah</h2>
            <h4>Digital Designer</h4>
            <p>An alternative designer who draws inspiration from the usual in an unusual way. Born on one continent and raised on another, the diversity of her background enriches her love of culture. She’s been in the presence of one of the Old 7 World Wonders and one of the New 7 World Wonders.</p>
            <p>Hebah’s love for knowledge stems from her grandmother, who learned how to read &amp; write in her 60’s, and learned how to drive a car in her 70’s.</p>
            <p>Hebah’s concepts are always a product of having the abnormally active curiosity gene. She actually believes that <em>“curiosity saved the cat.”</em></p>
            <p class="tsxl mbf tac">
              <a href="https://twitter.com/hebahbydesign/" class="tci mlxs mrxs"><svg class="icon"><use xlink:href="<%= image_url("icons.svg") %>#icon-twitter"></use></svg></a>
              <a href="https://instagram.com/hebahbydesign/" class="tci mlxs mrxs"><svg class="icon"><use xlink:href="<%= image_url("icons.svg") %>#icon-instagram"></use></svg></a>
              <a href="https://dribbble.com/HebaH" class="tci mlxs mrxs"><svg class="icon"><use xlink:href="<%= image_url("icons.svg") %>#icon-dribbble"></use></svg></a>
              <a href="https://www.pinterest.com/hebahbydesign/" class="tci mlxs mrxs"><svg class="icon"><use xlink:href="<%= image_url("icons.svg") %>#icon-pinterest"></use></svg></a>
            </p>
          </div>
          <div class="g-b--m--1of3 table-cell--m bca2 pal">
            <h2 class="mbf">Jessica Sunga</h2>
            <h4>Front-End Developer</h4>
            <p>A mediator between the sciences and arts. Perpetually pursuing to bridge the gap between technology and design in order to create systems that can be understood by everyone. Jessica is currently studying Front-End Development and UX Design to promote this.</p>
            <p>She believes that any problem can be solved by just opening your mind to other people's thoughts and actions. Because of the constant contact with interesting individuals, she continually learns everyday.</p>
            <p>Even through debating about the best typeface with a client or agonizing about the perfect timing for CSS animations, Jessica believes "every cloud has a silver-lining."</p>
            <p class="tsxl mbf tac">
              <a href="https://twitter.com/sngjss" class="tci mlxs mrxs"><svg class="icon"><use xlink:href="<%= image_url("icons.svg") %>#icon-twitter"></use></svg></a>
              <a href="https://github.com/sngjss" class="tci mlxs mrxs"><svg class="icon"><use xlink:href="<%= image_url("icons.svg") %>#icon-github"></use></svg></a>
            </p>
          </div>
        </div>
      </div>
      <div class="bca3 tci">
        <div class="cell cell--xs ptl pbl plm prm">
          <h2 class="tac">The Code<br><span class="tfb twb">&#8964;</span></h2>
          <p>Inspired by the TV comedy <em>How I Met Your Mother</em>’s Bro Code, The Gurl Code is meant to be light hearted and fun.</p>
          <p>The Gurl Code was crafted to unleash the power of the creative woman by allowing her to express herself through design. We then decided to spice it up with a little competition.</p>
          <p>If you’d like to participate in designing, or share a Gurl Code that you’d like to see designed, just drop us a line at <a href="mailto:team@gurlcode.com" class="tci">team@gurlcode.com</a> or contact us through our social media.</p>
          <h3 class="mbs">How it works</h3>
          <p>Two designers will be given a week to design The Gurl Code of the week. The designs will be up for 7 days and everyone is welcome to vote for the best design. The winner will then have bragging rights. In the future we hope to screen print the winner's design as their prize.</p>
        </div>
      </div>
      <div class="ptl pbl tac">
        <p class="plm prm tch">Connect with us to learn more about each week's Gurl Code, our artists, and how you can contribute.</p>

        <!-- Mailchimp's Form Code -->
        <form class="sub validate" action="//thegurlcode.us10.list-manage.com/subscribe/post?u=b3e798e446029870488f76e4f&amp;id=a390c56c44" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" target="_blank" novalidate>
          <div style="position: absolute; left: -5000px;"><input type="text" name="b_b3e798e446029870488f76e4f_a390c56c44" tabindex="-1" value=""></div>
          <p>
            <input type="email" value="" name="EMAIL" class="required email sub-email" id="mce-EMAIL" placeholder="EMAIL ADDRESS"><input type="submit" value="SUBSCRIBE" name="subscribe" id="mc-embedded-subscribe" class="sub-button">
          </p>

          <div id="mce-responses" class="clear">
            <div class="response" id="mce-error-response" style="display:none"></div>
            <div class="response" id="mce-success-response" style="display:none"></div>
          </div>
        </form>
        <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
      </div>

app/views/pages/gallery.html.erb
Gallery

app/views/pages/home.html.erb
      <div class="feature">
<% unless @submissions.nil? %>
  <% @submissions.each_with_index do |sub, index| %>
        <div class="feature-wrap">
          <div class="feature-img has-hover" style="background-image: url(<%= asset_path(sub.graphic.url) %>)" href="#">
            <div class="feature-hover">
              <div class="feature-vote">
    <% if user_signed_in? %>
      <% if current_user.recent_vote == @code.id %>
                <%= sub.votes %>
        <% percentage = sub.votes / @total %>
        <% if index == 0 %>
                <div class="half half--filled half--left"></div>
          <% if percentage >= 0.5 %>
                <div class="half half--filled half--left" data-rotate="<%= -(360 * (percentage - 0.5)).round %>"></div>
          <% else %>
                <div class="half half--empty half--right" data-rotate="<%= (360 * (0.5 - percentage)).round %>"></div>
          <% end %>
        <% else %>
                <div class="half half--filled half--right"></div>
          <% if percentage >= 0.5 %>
                <div class="half half--filled half--right" data-rotate="<%= (360 * (percentage - 0.5)).round %>"></div>
          <% else %>
                <div class="half half--empty half--left" data-rotate="<%= -(360 * (0.5 - percentage)).round %>"></div>
          <% end %>
        <% end %>
      <% else %>
                <%= link_to "Vote", vote_path(sub), method: :put, class: "tdn" %>
      <% end %>
    <% else %>
                <%= link_to "Vote", new_user_session_path, class: "tdn" %>
    <% end %>
              </div>
              <div class="feature-artist">
    <% if sub.website.present? %>
                <%= link_to (sub.artist.blank? ? "Anonymous" : sub.artist), sub.website, class: "tci" %>
    <% else %>
                <%= sub.artist.blank? ? "Anonymous" : sub.artist %>
    <% end %>
              </div>
    <% if sub.has_socials? %>
              <div class="feature-share">
      <% if sub.behance.present? %>
                <a href="<%= sub.behance %>"><svg class="icon icon-behance"><use xlink:href="<%= image_url("icons.svg") %>#icon-behance"></use></svg></a>
      <% end %>
      <% if sub.dribbble.present? %>
                <a href="<%= sub.dribbble %>"><svg class="icon icon-dribbble"><use xlink:href="<%= image_url("icons.svg") %>#icon-dribbble"></use></svg></a>
      <% end %>
      <% if sub.facebook.present? %>
                <a href="<%= sub.facebook %>"><svg class="icon icon-facebook"><use xlink:href="<%= image_url("icons.svg") %>#icon-facebook"></use></svg></a>
      <% end %>
      <% if sub.instagram.present? %>
                <a href="<%= sub.instagram %>"><svg class="icon icon-instagram"><use xlink:href="<%= image_url("icons.svg") %>#icon-instagram"></use></svg></a>
      <% end %>
      <% if sub.pinterest.present? %>
                <a href="<%= sub.pinterest %>"><svg class="icon icon-pinterest"><use xlink:href="<%= image_url("icons.svg") %>#icon-pinterest"></use></svg></a>
      <% end %>
      <% if sub.twitter.present? %>
                <a href="<%= sub.twitter %>"><svg class="icon icon-twitter2"><use xlink:href="<%= image_url("icons.svg") %>#icon-twitter"></use></svg></a>
      <% end %>
              </div>
    <% end %>
            </div>
          </div>
        </div>
  <% end %>
<% end %>
      </div>