config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { omniauth_callbacks: "users" }

  root 'pages#home'
  get 'about', to: 'pages#about', as: 'about'
  get 'gallery', to: 'pages#gallery', as: 'gallery'
  # root 'pages#coming_soon'
  # get 'home', to: 'pages#home', as: 'home'
  get 'coming_soon', to: 'pages#coming_soon', as: 'coming_soon'

  resources :codes, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :submissions, only: [:new, :create, :edit, :update, :destroy]
    member do
      put 'queue', as: 'queue'
      put 'dequeue', as: 'dequeue'
    end
  end

  put 'submissions/:id/vote', to: 'submissions#vote', as: 'vote'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/code.rb
class Code < ActiveRecord::Base
  has_many :submissions

  validates :title, presence: true
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController

  def index

    unless can? :index, Code
      return redirect_to root_path, alert: "You aren't allowed to view codes."
    end

    @feature = Code.includes(:submissions).where(status: "Featured").first
    @queued = Code.includes(:submissions).where(status: "Queued")
    @codes = Code.includes(:submissions).where.not(status: ["Queued", "Used", "Featured"])
  end

  def new

    unless can? :create, Code
      return redirect_to root_path, alert: "You aren't allowed to create codes."
    end

    @code = Code.new
  end

  def create

    unless can? :create, Code
      return redirect_to root_path, alert: "You aren't allowed to create codes."
    end

    @code = Code.create(code_params)

    if @code.persisted?
      redirect_to codes_path, notice: "Code created successfully!"
    else
      render :new
    end
  end

  def edit

    @code = Code.find(params[:id])

    unless can? :update, @code
      return redirect_to root_path, alert: "You aren't allowed to edit codes."
    end
  end

  def update

    @code = Code.find(params[:id])

    unless can? :update, @code
      return redirect_to root_path, alert: "You aren't allowed to edit codes."
    end

    if @code.update(code_params)
      redirect_to codes_path, notice: "Code updated successfully!"
    else
      render :edit
    end
  end

  def destroy

    @code = Code.find(params[:id])

    unless can? :destroy, @code
      return redirect_to root_path, alert: "You aren't allowed to delete codes."
    end

    if @code.destroy
      redirect_to codes_path, notice: "Code removed successfully!"
    else
      redirect_to codes_path, alert: "Error: Code could not be removed."
    end
  end

  def queue

    @code = Code.find(params[:id])

    unless can? :queue, @code
      return redirect_to root_path, alert: "You aren't allowed to queue codes."
    end

    if @code.update(status: "Queued")
      redirect_to codes_path, notice: "Code queued successfully!"
    else
      redirect_to codes_path, alert: "Error: Code could not be queued."
    end
  end

  def dequeue

    @code = Code.find(params[:id])

    unless can? :dequeue, @code
      return redirect_to root_path, alert: "You aren't allowed to dequeue codes."
    end

    if @code.update(status: "")
      redirect_to codes_path, notice: "Code dequeued successfully!"
    else
      redirect_to codes_path, alert: "Error: Code could not be dequeued."
    end
  end


  private

  def code_params
    params.require(:code).permit!
  end
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/views/codes/_form.html.erb
<div>
  <%= form_for @code do |f| %>
    <div class="group">
      <div class="g-b <%= @code.submissions.any? ? "g-b--m--1of2" : "" %> plm prm">
        <div class="field is-required">
          <%= f.label :title %><br>
          <%= f.text_field :title %>
        </div>
        <div class="field">
          <%= f.label :message %><br>
          <%= f.text_area :message, class: "textarea" %>
        </div>
      </div>
<% if @code.submissions.any? %>
      <div class="g-b <%= @code.submissions.any? ? "g-b--m--1of2" : "" %> plm prm">
        <h3>Current <%= pluralize!(@code.submissions.size, "Submission") %></h3>
        <div class="group">
  <% count = @code.submissions.size %>
  <% @code.submissions.each do |sub| %>
          <div class="g-b g-b--1of<%= count %> paf">
    <% if sub.graphic.present? %>
            <img src="<%= asset_path(sub.graphic.url) %>" alt="Submission">
    <% else %>
            <p><em>No graphic present.</em></p>
    <% end %>
            <p class="tac"><%= link_to "Edit", edit_code_submission_path(@code, sub), class: "button button--b" %></p>
          </div>
  <% end %>
        </div>
      </div>
<% end %>
    </div>

    <div class="field pam">
      <%= f.submit class: "button button--a" %>
      <%= link_to "Go Back", codes_path, class: "button button--b" %>
    </div>
  <% end %>
</div>

app/views/codes/edit.html.erb
<%= title("Edit Code") %>
      <div class="cell cell--s">
        <h1 class="pls prs">Editing "<%= @code.title.truncate(20, omission: "...", separator: " ") %>"</h1>
        <%= render 'form' %>
      </div>

app/views/codes/index.html.erb
<% title "Codes" %>
      <div class="cell plm prm">
        <div class="mbm"><%= link_to "Create New", new_code_path, class: "button button--a" %></div>
<% if @feature.present? %>
  <% code = @feature %>
        <div class="list">
          <div class="subtitle">Featured Code</div>
          <div class="list-item mbm">
            <div class="list list--inline list--flex">
              <div class="list-item list-item--grow ellipsis mrm">
                <%= code.title %><br>
                <span class="tsxs"><%= pluralize(code.submissions.size, "submission") %></span>
              </div>
              
              <%= link_to edit_code_path(code), class: "list-item", title: "Edit" do %>
                <svg class="icon icon-edit"><use xlink:href="<%= image_url("icons.svg") %>#icon-edit"></use></svg>
              <% end %>
            </div>
          </div>
        </div>
<% end %>

<% if @queued.any? %>
        <div class="list">
          <div class="subtitle">Queued <%= pluralize!(@queued.size, "Code") %></div>
  <% @queued.each do |code| %>
          <div class="list-item mbm">
            <div class="list list--inline list--flex">
              <div class="list-item list-item--grow ellipsis mrm">
                <%= code.title %><br>
                <span class="tsxs"><%= pluralize(code.submissions.size, "submission") %></span>
              </div>
              <%= link_to edit_code_path(code), class: "list-item mrm", title: "Edit" do %>
                <svg class="icon icon-edit"><use xlink:href="<%= image_url("icons.svg") %>#icon-edit"></use></svg>
              <% end %>
              <%= link_to new_code_submission_path(code), class: "list-item mrm", title: "Submit Graphic" do %>
                <svg class="icon icon-upload"><use xlink:href="<%= image_url("icons.svg") %>#icon-upload"></use></svg>
              <% end %>
              <%= link_to dequeue_code_path(code), method: :put, class: "list-item mrm", title: "Dequeue" do %>
                <svg class="icon icon-redo"><use xlink:href="<%= image_url("icons.svg") %>#icon-redo"></use></svg>
              <% end %>
              <%= link_to edit_code_path(code), method: :delete, class: "list-item", title: "Remove", data: {confirm: "Are you sure you want to remove the code \"#{code.title}\"?"} do %>
                <svg class="icon icon-cross"><use xlink:href="<%= image_url("icons.svg") %>#icon-cross"></use></svg>
              <% end %>
            </div>
          </div>
  <% end %>
        </div>
<% end %>

<% if @codes.any? %>
        <div class="list">
          <div class="subtitle">Other <%= pluralize!(@codes.size, "Code") %></div>
  <% @codes.each do |code| %>
          <div class="list-item mbm">
            <div class="list list--inline list--flex">
              <div class="list-item list-item--grow ellipsis mrm">
                <%= code.title %><br>
                <span class="tsxs"><%= pluralize(code.submissions.size, "submission") %></span>
              </div>
              <%= link_to edit_code_path(code), class: "list-item mrm", title: "Edit" do %>
                <svg class="icon icon-edit"><use xlink:href="<%= image_url("icons.svg") %>#icon-edit"></use></svg>
              <% end %>
              <%= link_to new_code_submission_path(code), class: "list-item mrm", title: "Submit Graphic" do %>
                <svg class="icon icon-upload"><use xlink:href="<%= image_url("icons.svg") %>#icon-upload"></use></svg>
              <% end %>
              <%= link_to queue_code_path(code), method: :put, class: "list-item mrm", title: "Queue" do %>
                <svg class="icon icon-check"><use xlink:href="<%= image_url("icons.svg") %>#icon-check"></use></svg>
              <% end %>
              <%= link_to edit_code_path(code), method: :delete, class: "list-item", title: "Remove", data: {confirm: "Are you sure you want to remove the code \"#{code.title}\"?"} do %>
                <svg class="icon icon-cross"><use xlink:href="<%= image_url("icons.svg") %>#icon-cross"></use></svg>
              <% end %>
            </div>
          </div>
  <% end %>
        </div>
<% end %>
      </div>

app/views/codes/new.html.erb
<%= title("Create Code") %>
      <div class="cell cell--xs">
        <h1>Create a Code</h1>
        <%= render 'form' %>
      </div>