config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { omniauth_callbacks: "users" }

  root 'pages#home'
  get 'about', to: 'pages#about', as: 'about'
  get 'gallery', to: 'pages#gallery', as: 'gallery'
  # root 'pages#coming_soon'
  # get 'home', to: 'pages#home', as: 'home'
  get 'coming_soon', to: 'pages#coming_soon', as: 'coming_soon'

  resources :codes, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :submissions, only: [:new, :create, :edit, :update, :destroy]
    member do
      put 'queue', as: 'queue'
      put 'dequeue', as: 'dequeue'
    end
  end

  put 'submissions/:id/vote', to: 'submissions#vote', as: 'vote'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_footer.html.erb
  <footer class="footer">
    <div class="cell cell--xs pam">
      <div class="fr tsl">
<% if user_signed_in? && current_user.role == "Admin" %>
        <%= link_to "Codes", codes_path, class: "tdn mrm" %>
        <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "tdn" %>
<% else %>
        <a href="https://instagram.com/the_gurlcode/" class="tci mlm"><svg class="icon"><use xlink:href="<%= image_url("icons.svg") %>#icon-instagram"></use></svg></a>
        <a href="https://www.pinterest.com/TheGurlCode/" class="tci mlm"><svg class="icon"><use xlink:href="<%= image_url("icons.svg") %>#icon-pinterest"></use></svg></a>
        <a href="https://twitter.com/the_gurlcode/" class="tci mlm"><svg class="icon"><use xlink:href="<%= image_url("icons.svg") %>#icon-twitter"></use></svg></a>
<% end %>
      </div>
      <div>&copy; The Gurl Code</div>
    </div>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-55626793-3', 'auto');
      ga('send', 'pageview');
    </script>
  </footer>

app/views/layouts/_header.html.erb
<% unless current_page?(controller: "/pages", action: "coming_soon") %>
      <header class="header">
        <nav class="nav list list--inline list--flex">
  <% if current_page?(controller: "/pages", action: "gallery") %>
          <!-- <%= link_to "Gallery", gallery_path, class: "nav-item list-item is-active" %> -->
  <% else %>
          <!-- <%= link_to "Gallery", gallery_path, class: "nav-item list-item" %> -->
  <% end %>
          <%= link_to "Sign In", new_user_session_path, class: "nav-item list-item" %>
          <%= link_to root_path, class: "nav-item nav-feature list-item " do %>
            Gurl C<svg class="icon icon-asterisk"><use xlink:href="<%= image_url("icons.svg") %>#icon-asterisk"></use></svg>de
          <% end %>
  <% if current_page?(controller: "/pages", action: "about") %>
          <%= link_to "About", about_path, class: "nav-item list-item is-active" %>
  <% else %>
          <%= link_to "About", about_path, class: "nav-item list-item" %>
  <% end %>
        </nav>
        <div class="header-tab"></div>
      </header>
<% end %>

app/views/layouts/_messages.html.erb
<% if flash.any? %>
      <div>
  <% flash.each do |type, message| %>
        <noscript>
          <div class="msg msg--noscript msg--<%= type %>">
            <%= message %>
          </div>
        </noscript>

        <div class="msg msg--<%= type %>">
          <%= message %>
        </div>
  <% end %>
      </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title><%= content_for?(:title) ? content_for(:title) : "Gurl Code" %></title>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <!--[if lte IE 9]>
      <%= stylesheet_link_tag "ie", media: "all", "data-turbolinks-track" => true %>
    <![endif]-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="main por">
<%= render 'layouts/header' %>
<%= render 'layouts/messages' %>
<%= yield %>
<%= render 'layouts/footer' %>
    </div>
  </body>
</html>